tasks:
  - name: terraform
    env:
      TF_LOG: DEBUG  
    before: |
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credentials
      source ./bin/set_tf_alias
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
      source ./bin/build_provider
      clear
  - name: sinatra
    before: | 
      cd terratowns_mock_server
      bundle install
      bundle exec ruby server.rb       
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli
      source ./bin/set_tf_alias
      clear
  - name: http-server
    before: |
      npm install --global http-server
    command: 
      http-server      
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - phil294.git-log--graph
    - mhutchie.git-graph